version: '3.7'

services:
  metasearch2:
    build:
      args:
        CONFIG: "/usr/local/bin/config.toml"
      context: .
      dockerfile: Containerfile
    network_mode: "host"
    restart: unless-stopped