bind = "0.0.0.0:28019"

[engines]
google = { weight = 1.05 }
bing = { weight = 1.0 }
brave = { weight = 1.25 }

google-scholar = { enabled = false, weight = 0.50 }
rightdao = { enabled = false, weight = 0.10 }
stract = { enabled = false, weight = 0.15 }
yep = { enabled = false, weight = 0.10 }

# calculators (give them a high weight so they're always the first thing in autocomplete)
numbat = { weight = 10 }
fend = { enabled = false, weight = 10 }

[engines.marginalia]
args = { profile = "corpo", js = "default", adtech = "default" }
weight = 0.15
