name: Push to Docker hub

on:
  push:
    branches: ["main"]

jobs:
  docker-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      # Sets ${{ steps.version.outputs.VERSION }}
      - name: Retrieve version
        run: |
          echo "VERSION=$(cargo pkgid | cut -d "@" -f2)" >> $GITHUB_OUTPUT
        id: version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build, and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/metasearch2:latest, ${{ secrets.DOCKERHUB_USERNAME }}/metasearch2:${{ steps.version.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64/v8
